export const languageLabels = {
  en: {
    action: "Action",
    and: "and",
    ballModel: "Ball model",
    ballModelPath: "Ball model path",
    browse: "Browse",
    calibrateTable: "Calibrate Table",
    calibratingTable: "Click four table corners on the video",
    camera: "Camera",
    clearTrajectory: "Delete Video",
    confidence: "Pose detection confidence",
    dark: "Dark",
    language: "中文",
    light: "Light",
    openSource: "Open source",
    poseModel: "Pose model",
    poseModelPath: "Pose model path",
    save: "Save",
    saveFrameDirectory: "Save frame directory",
    saveFrame: "Save Frame",
    saved: "Saved",
    selectSource: "Select a video or camera",
    settings: "Settings",
    start: "Play",
    status: "Video information",
    stop: "Stop",
    tableAutoCalibration: "Auto detect table",
    tableManualCalibration: "Manual table annotation",
    tableModelPath: "Table model path",
    tableNeedSource: "Open a video before table calibration",
    tableNeedStopped: "Stop the video before table calibration",
    switchToDark: "Switch to dark mode",
    switchLanguage: "Switch to Chinese",
    switchToLight: "Switch to light mode",
    video: "Video",
    videoDuration: "Duration",
    videoFileSize: "File size",
    videoFps: "FPS",
    videoFrames: "Frames",
    videoName: "Name",
    videoSize: "Resolution",
    videos: "Videos",
    yoloModels: "YOLO Models",
  },
  zh: {
    action: "动作",
    and: "和",
    ballModel: "球模型",
    ballModelPath: "球模型路径",
    browse: "浏览",
    calibrateTable: "校准球台",
    calibratingTable: "请在视频上点击球台四个角",
    camera: "摄像头",
    clearTrajectory: "删除视频",
    confidence: "人物姿态识别置信度",
    dark: "夜间",
    language: "English",
    light: "白天",
    openSource: "打开来源",
    poseModel: "姿态模型",
    poseModelPath: "姿态模型路径",
    save: "保存",
    saveFrameDirectory: "保存帧目录",
    saveFrame: "保存帧",
    saved: "已保存",
    selectSource: "选择视频或摄像头",
    settings: "设置",
    start: "播放",
    status: "视频信息",
    stop: "停止",
    tableAutoCalibration: "自动识别球桌位置",
    tableManualCalibration: "手动标注球桌位置",
    tableModelPath: "球桌模型路径",
    tableNeedSource: "请先打开视频",
    tableNeedStopped: "请先停止视频",
    switchToDark: "切换到夜间模式",
    switchLanguage: "切换到英文",
    switchToLight: "切换到白天模式",
    video: "视频",
    videoDuration: "时长",
    videoFileSize: "文件大小",
    videoFps: "帧率",
    videoFrames: "帧数",
    videoName: "名称",
    videoSize: "分辨率",
    videos: "视频",
    yoloModels: "YOLO 模型",
  },
};

export const defaultLanguage = "en";
